# Generated by Django 5.0 on 2024-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
